### ISSUE TITLE
[SDL_Mixer_X] binary unable to locate library

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#10]
built Uncapped Plus with Discord RPC and Mixer X
I get this error when trying to launch:
```
srb2ucp: error while loading shared libraries: libSDL2_mixer_ext.so.2: cannot open shared object file: No such file or directory
```

**Comment by pinkcreeper100** [comment]
yet I can find it in `/usr/local/lib`

**Comment by Bijman** [comment]
Did you set `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` in your shell configuration file? This should solve issue with finding path to library by binary.

**Comment by pinkcreeper100** [comment]
could I use direnv for that instead?

**Comment by Bijman** [comment]
Yes.

**Comment by pinkcreeper100** [comment]
exporting that environment variable worked, thanks
