### ISSUE TITLE
[SDL_Mixer-X] use custom libgme

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#13]
include a custom libgme that uses MAME rather than Nuked-OPN2 when building with Mixer X

**Comment by pinkcreeper100** [comment]
[reasoning](https://bitbucket.org/mpyne/game-music-emu/issues/32/gym-playback-struggles-significantly-with)

**Comment by pinkcreeper100** [comment]
Ignore previous message that I deleted

**Comment by Bijman** [comment]
Implemented support for compiling libgme with MAME YM2612 emulator (commit 3d7a241) in order to have better compatibility with libSDL2_Mixer_X.
