### ISSUE TITLE
[Suggestion] Flatpak build option for Linux

### ISSUE THREAD

**Issue by jSQrD-dev** [Bijman/srb2bld#15]
This is both a question and a feature request. Is it possible to add a build option to create a Flatpak?

**Comment by Bijman** [comment]
Maybe. Unfortunately I have yet to have any experience with making Flatpaks to implement this feature. But perhaps in the future could be possible.

**Comment by Bijman** [comment]
Implemented option to build Flatpaks using option -f/--flatpak with commit eb2fd35
