### ISSUE TITLE
i cant compile this

### ISSUE THREAD

**Issue by RealYamTalOren** [Bijman/srb2bld#18]
i can get past the 6 steps and nothing more any help?

**Comment by pinkcreeper100** [comment]
Please can you provide more context?

**Comment by RealYamTalOren** [comment]
Open Git Bash (✅ obv)

Go to your user directory (usually "C:/Users/[your username]"): cd ~ (✅)

Enter git clone https://github.com/Bijman/srb2bld (✅)

Create directory "bin" with command: mkdir ~/bin (✅)

Copy script to "~/bin": cp ~/srb2bld/srb2bld ~/bin (✅)

Change script's permissions to be executable: chmod 755 ~/bin/srb2bld (✅)

Open text editor for "~/.bash_profile": nano ~/.bash_profile, (stuck in here)

In the opened text editor from previous step write new path to executables with environment variable PATH like export PATH="~/bin:$PATH" in "~/.bash_profile" (cant enter)

Enter source ~/.bash_profile or restart Git Bash. (^)

**Comment by Bijman** [comment]
You need to type `nano ~/.bash_profile` , so it will open file ".bash_profile" in Git Bash and then write `export PATH="~/bin:$PATH"` or paste copied line with right mouse button to this file, then you can press ctrl+s to save file and ctrl+x to quit nano. Alternatively, if my tip didn't help, then you can simply write this line export PATH="~/bin:$PATH"` in standard Windows Notepad in path `C:\Users\[YOUR-USERNAME]/.bash_profile` and save file.

**Comment by RealYamTalOren** [comment]
https://github.com/Bijman/srb2bld/assets/124284338/82167bfe-d095-4614-b936-d3a07ddba7f7

ur answer is in the url (spoiler: nothing worked not even google)

**Comment by Bijman** [comment]
From the video I see that you are pressing ctrl+t to get prompt for executing commands in the text editor nano, you don't need to do that. You only need to paste this line in file .bash_profile, then save file with shortcut keys `ctrl+s` and then exit text editor with `ctrl+x` and then execute commands from instructions.

**Comment by RealYamTalOren** [comment]
https://github.com/Bijman/srb2bld/assets/124284338/b91ac62f-3eb0-4ff6-85b9-b67dc2ef0930

**Comment by RealYamTalOren** [comment]
and yes i did the chmod 755 ~/bin/srb2bld

**Comment by Bijman** [comment]
> Desktop.2023.06.09.-.11.50.51.01.mp4

Move **bin** folder from path **C:\Users\USER\srb2bld** to path **C:\Users\USER**, so **srb2bld** file will be in correct path **C:\Users\USER\bin**.  Then read further instructions.

**Comment by RealYamTalOren** [comment]
![image](https://github.com/Bijman/srb2bld/assets/124284338/6fac1805-f151-4493-b433-3b8d9c8ffb08)

**Comment by RealYamTalOren** [comment]
and yes i did what u told me @Bijman

**Comment by RealYamTalOren** [comment]
nvm i did the wrong command

**Comment by RealYamTalOren** [comment]
but it still did not work

**Comment by RealYamTalOren** [comment]
proof:
![image](https://github.com/Bijman/srb2bld/assets/124284338/f9f09146-a384-4fc6-9ace-85c241318ea5)

**Comment by Bijman** [comment]
Show me output of `echo $PATH` and `ls -hAlF ~/bin/srb2bld`

**Comment by RealYamTalOren** [comment]
https://github.com/Bijman/srb2bld/assets/124284338/b78a8cfb-5813-41d6-b626-00488db6fb4f

fixed the prev thing

**Comment by RealYamTalOren** [comment]
but it still lead me to this

**Comment by RealYamTalOren** [comment]
and i am on windows

**Comment by Bijman** [comment]
> Desktop.2023.07.04.-.13.36.58.01.mp4
> 
> fixed the prev thing

MSYS environment and MSYS2 program is not recognized by `srb2bld`, that is why you have this message. 
I created a new issue #20 to add support for these two.

In the meantime, please try again with Git Bash.

**Comment by Bijman** [comment]
No reason to keep this issue open. Added support for MSYS with commit eb2fd35.
