### ISSUE TITLE
[Suggestion] Adding SRB2Kart-Galaxy as a Build Target

### ISSUE THREAD

**Issue by jSQrD-dev** [Bijman/srb2bld#19]
https://mb.srb2.org/addons/srb2kart-galaxy.4500/
https://git.do.srb2.org/Galactice/Kart-Public/-/tree/Galaxy-Redux

**Comment by Bijman** [comment]
WIP. Definitely I would like to add this great build to `srb2bld`.

**Comment by Bijman** [comment]
Added SRB2 Kart Galaxy as new build target with commit eb2fd35.
