### ISSUE TITLE
Issue building SLADE - connectiion error with ppa.launchpad.net in Docker container

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#2]
https://asciinema.org/a/D2WWzdBaOfyikHTubQEnAovOv

**Comment by Bijman** [comment]
This is more like an error with connecting to `ppa.launchpad.net` for installing additional packages in container, based on your output:
```
W: Failed to fetch http://ppa.launchpad.net/apt-fast/stable/ubuntu/dists/bionic/InRelease  Could not res
olve 'ppa.launchpad.net'
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/bionic/InRelease  Could
 not resolve 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
which could mean a few things.

Could you retry and confirm this same issue still persists, so we would know, if this was temporary with server connection on your end. 

If not, something is blocking access to `ppa.launchpad.net` within container or/and your host system. Could you provide output of `ping -c 3 ppa.launchpad.net` and `dig ppa.launchpad.net -t ANY +nocmd` from your host system? Also output of connection within container with: `docker run --rm --security-opt="label:disable" ubuntu:22.04 bash -c 'apt update ; apt install -y iputils-ping dnsutils ; printf "\e[1;93m\n%s\e\n[0m" "##PING##" ; ping -c 3 ppa.launchpadcontent.net ; printf "\e[1;93m\n%s\n\e[0m" "##DIG##" ; dig ppa.launchpad.net -t ANY +nocmd'` would be welcome.

**Comment by pinkcreeper100** [comment]
https://asciinema.org/a/t2eGpy82qAJ2EfT6X9kp5fLBK
it might have been an error with the servers at the time, I'll try building slade again

**Comment by pinkcreeper100** [comment]
it launches

**Comment by Bijman** [comment]
OK. I will close issue.
