### ISSUE TITLE
Local Asset Path isn't actually supported when making AppImages

### ISSUE THREAD

**Issue by EeveeEuphoria** [Bijman/srb2bld#22]
While trying to compile srb2 2212 pre2 (still isn't working, had to remove that sdl_openurl line) I tried to point the asset file to a local one, since the prompt for it claims it supports it:

```
Please enter Sonic Robo Blast 2's assets path, or just press enter to download and extract the latest SRB2/SRB2Kart stable release assets. Supported links/paths:

        ...

        - full path to downloaded archived file in formats supported by p7zip (https://www.7-zip.org) or full path to directory with build's assets, for example /home/zesi/Downloads/SRB2.zip for Linux and macOS or C:\Downloads\SRB2.zip for Windows.
```
When I try to do just that, i.e. point to `/home/zesi/Downloads/srb2win_v2212-pre2.zip`, it straight up doesn't work, and produces an AppImage without those assets bundled in. However when I supply, say, a Google Drive link, that works fine. Not sure what's up with that, but, it's definitely a bug.

**Comment by Bijman** [comment]
Hello. Once again thanks for reporting issue. I made commit 6c34f02 that hopefully will work for you. Let me know, if it solved your issue. :)

**Comment by EeveeEuphoria** [comment]
Tested this, it does seem to work thankfully!

**Comment by Bijman** [comment]
Ok. I will close issue then.
