### ISSUE TITLE
"x86_64-w64-mingw32-gcc-10-win32: No such file or directory" when compiling on Windows

### ISSUE THREAD

**Issue by Bijman** [Bijman/srb2bld#25]
https://github.com/Bijman/srb2bld/assets/146545399/56568f7a-bfad-4fb4-8474-2445fb59976a

its not fixed (somehow)

_Originally posted by @LegoLuigiJumpscare in https://github.com/Bijman/srb2bld/issues/24#issuecomment-1744426097_

**Comment by LegoLuigiJumpscare** [comment]
can u make it so it always compiles and installs on the latest srb2 version?

**Comment by Bijman** [comment]
By default, if you enter `srb2bld -i`, then choose build and then just press enter when you are asked about choosing branch, in the result you have the latest development version of SRB2. You can then enter `srb2bld -up` to upgrade build. But that's outside of issue, so I will close the ticket.
