### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LegoLuigiJumpscare** [Bijman/srb2bld#27]
![image](https://github.com/Bijman/srb2bld/assets/146545399/44e2b73b-72e2-4057-bc1d-a157312cae6b)

**Comment by Bijman** [comment]
Please update script to the latest commit version. That was fixed in previous commit in November.

**Comment by LegoLuigiJumpscare** [comment]
thx

**Comment by Bijman** [comment]
I will close ticket.
