### ISSUE TITLE
Final Demo Dependency Hell

### ISSUE THREAD

**Issue by vyvir** [Bijman/srb2bld#29]
OpenSUSE Leap 15.6 dropped `libSDL2_mixer-2_0-0-32bit` from its repos.
OpenSUSE Tumbleweed dropped both `libSDL2_mixer-2_0-0-32bit` and `libmodplug1-32bit`.

I filed a report on Bugzilla, however it seems they won't be included again.
https://bugzilla.opensuse.org/show_bug.cgi?id=1227467

This poses an issue - without manual installation of these old packages, Final Demo is currently unrunnable on OpenSUSE, and I assume it will be the case for other distros too.

**Comment by Bijman** [comment]
What I can do is to provide 32-bit libraries from container, either from packages or compiled from source, to host in path "/usr/local", so it will be possible to run Final Demo.

Alternatively, you can create Final Demo AppImage, so it will run game with included 32-bit libraries within AppImage.

**Comment by Bijman** [comment]
From commit 93db143 all 32-bit libraries required for SRB2 Final Demo and SRB2 JTE are copied to host from container to solve issue of missing 32-bit packages.
