### ISSUE TITLE
When installing Final Demo, 3drend.dll is not installed

### ISSUE THREAD

**Issue by vyvir** [Bijman/srb2bld#30]
3drend.dll contains all the assets for Christmas Mode. 
2.0 removes it, but Final Demo won't work on Dec 25th without it.
I checked and when the file is included, the game does run.

**Comment by Bijman** [comment]
Thank you for reporting this isue. Included installing "3drend.dll" from extracted SRB2 Final Demo assets in commit d209827f1.
