### ISSUE TITLE
Error installing dependencies on nixos-unstable

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#6]
```
Installing missing dependencies for Sonic Robo Blast 2 Custom srb2ucpr to the system. Please wait...
installing 'nix-index-unstable-2022-03-07'
this derivation will be built:
  /nix/store/2x8m03b23kw9cxmi209xy89v6js0r45s-nix-index-unstable-2022-03-07.drv
this path will be fetched (2.37 MiB download, 11.20 MiB unpacked):
  /nix/store/ir90192wdrk5da5p880cxxz8kd06f8lq-nix-index-unstable-2022-03-07
copying path '/nix/store/ir90192wdrk5da5p880cxxz8kd06f8lq-nix-index-unstable-2022-03-07' from 'https://cache.nixos.org'...
building '/nix/store/2x8m03b23kw9cxmi209xy89v6js0r45s-nix-index-unstable-2022-03-07.drv'...
error: this derivation has bad 'meta.outputsToInstall'

```

**Comment by pinkcreeper100** [comment]
oh and on the topic of nixos `/usr/local/bin` isn't on `$PATH` by default

**Comment by Bijman** [comment]
This is an issue with `nix-index` installed from NixOS unstable repository or something else related to options in your `configuration.nix` or conflicting packages set in your NixOS system.
Update system with `sudo nix-channel --update` and `sudo nix-rebuild switch --upgrade-all` and `nix-env -u`: https://github.com/NixOS/nixpkgs/issues/88690

I tried to reproduce this, but I can't get the same results:
https://i.imgur.com/0fCkpon.png
