### ISSUE TITLE
[Enhancement] Alternative installation locations

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#8]
e.g. `$HOME/.local/bin` or `$HOME/bin`
As NixOS doesn't have `/usr`

**Comment by Bijman** [comment]
This is something I'm working on it, since immutable systems gained popularity thanks to Steam Deck's SteamOS and Fedora Silverblue.

**Comment by Bijman** [comment]
Added option --user/-u with commit 7d971cf (executed with `srb2bld -i -u`) to install to user's local path `$HOME/.local/bin`.
